Sigma.LendFoundry.Rules.Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sigma.LendFoundry.Rules.Client.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("ClientHome");
        }

        public ActionResult ClientHome()
        {
            return View("ClientHome");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Sigma.LendFoundry.Rules.Client/Controllers/RuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sigma.LendFoundry.Rules.Client.Controllers
{
    public class RuleController : Controller
    {
        //
        // GET: /Rule/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateRule()
        {
            return View();
        }


        public ActionResult GetAllRules()
        {
            return View("RuleList");
        }
	}
}

Sigma.LendFoundry.Rules.Client/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Sigma.LendFoundry.Rules.Client/Views/Home/ClientHome.cshtml
@{
    ViewBag.Title = "Lendfoundry Rules Test Client Home Page";
}

<div class="text-center">
    <h1>Lendfoundry Rules Engine</h1>
    <p class="lead">TEST HARNESS</p>
</div>

<div>
    <table class="table-bordered" align="center">
        <thead>
            <tr>
                <th class="text-center">
                    <b>Rule API</b>
                </th>
            </tr>
        </thead>
        <tr>
            <td>@Html.ActionLink("Create Rule", "CreateRule", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Update Rule", "UpdateRule", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Get Rule Details", "GetRuleDetails", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Get All Rules", "GetAllRules", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Delete Rule", "DeleteRule", "Rule")</td>
        </tr>
    </table>
</div>

<div>
    <table class="table-bordered" align="center">
        <thead>
            <tr>
                <th class="text-center">
                    <b>Variables API</b>
                </th>
            </tr>
        </thead>
        <tr>
            <td>@Html.ActionLink("Create Variable", "CreateVariable", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Update Variable", "UpdateVariable", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Get Variable Details", "GetVariableDetails", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Get All Variables", "GetAllVariables", "Rule")</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Delete Variable", "DeleteVariable", "Rule")</td>
        </tr>
    </table>
</div>

Sigma.LendFoundry.Rules.Client/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sigma.LendFoundry.Rules.Client/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Sigma.LendFoundry.Rules.Client/Views/Rule/CreateRule.cshtml
@model Sigma.LendFoundry.Rules.Core.Models.Rule

@{
    ViewBag.Title = "CreateRule";
}

<h2>CreateRule</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rule</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expression, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Expression)
                @Html.ValidationMessageFor(model => model.Expression)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy)
                @Html.ValidationMessageFor(model => model.CreatedBy)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedBy)
                @Html.ValidationMessageFor(model => model.UpdatedBy)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Sigma.LendFoundry.Rules.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LendFoundry Rules Engine", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create Rule", "CreateRule", "Rule")</li>
                    <li>@Html.ActionLink("Get Rule Details", "GetRuleDetails", "Rule")</li>
                    <li>@Html.ActionLink("Get All Rules", "GetAllRules", "Rule")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sigma Info Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>